version: "3.7"
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-test
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysqldb


  postgres:
    image: postgres:14.4
    restart: unless-stopped
    networks:
      - bored-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  sonarqube:
    image: sonarqube:8.9.7-community
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - bored-network
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins


  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus:/nexus-data
    networks:
      - bored-network
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    networks:
      - bored-network
    restart: unless-stopped
    volumes:
      - prometheus:/var/lib/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    networks:
      - bored-network
    restart: unless-stopped
    volumes:
      - graf:/var/lib/graf
networks:
  bored-network:
    name: bored-network
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonarqube_db:
  postgresql_data:
  mysqldb:
  nexus:
  prometheus:
  graf: